<?php

namespace App\Enums;

use BenSampo\Enum\Enum;

final class Surah extends Enum
{
    const AL_FATIHAH = 1;
    const AL_BAQARAH = 2;
    const ALI_IMRAN = 3;
    const AN_NISA = 4;
    const AL_MAIDAH = 5;
    const AL_ANAM = 6;
    const AL_ARAF = 7;
    const AL_ANFAL = 8;
    const AT_TAUBAH = 9;
    const YUNUS = 10;
    const HUD = 11;
    const YUSUF = 12;
    const AR_RAD = 13;
    const IBRAHIM = 14;
    const AL_HIJR = 15;
    const AN_NAHL = 16;
    const AL_ISRA = 17;
    const AL_KAHF = 18;
    const MARYAM = 19;
    const TAHA = 20;
    const AL_ANBIYA = 21;
    const AL_HAJJ = 22;
    const AL_MUUMINUN = 23;
    const AN_NUR = 24;
    const AL_FURQAN = 25;
    const ASH_SHUARA = 26;
    const AN_NAML = 27;
    const AL_QASAS = 28;
    const AL_ANKABUT = 29;
    const AR_RUM = 30;
    const LUQMAN = 31;
    const AS_SAJDAH = 32;
    const AL_AHZAB = 33;
    const SABA = 34;
    const FATIR = 35;
    const YA_SIN = 36;
    const ASH_SAFFAT = 37;
    const SAD = 38;
    const AZ_ZUMAR = 39;
    const GHAFIR = 40;
    const FUSSILAT = 41;
    const ASH_SHURA = 42;
    const AZ_ZUKHRUF = 43;
    const AD_DUKHAN = 44;
    const AL_JATHIYA = 45;
    const AL_AHQAF = 46;
    const MUHAMMAD = 47;
    const AL_FATH = 48;
    const AL_HUJURAT = 49;
    const QAF = 50;
    const ADH_DHARIYAT = 51;
    const AT_TUR = 52;
    const AN_NAJM = 53;
    const AL_QAMAR = 54;
    const AR_RAHMAN = 55;
    const AL_WAQIA = 56;
    const AL_HADID = 57;
    const AL_MUJADILA = 58;
    const AL_HASHR = 59;
    const AL_MUMTAHINA = 60;
    const AS_SAFF = 61;
    const AL_JUMUAH = 62;
    const AL_MUNAFIQUN = 63;
    const AT_TAGHABUN = 64;
    const AT_TALAQ = 65;
    const AT_TAHRIM = 66;
    const AL_MULK = 67;
    const AL_QALAM = 68;
    const AL_HAAQQA = 69;
    const AL_MAARIJ = 70;
    const NUH = 71;
    const AL_JINN = 72;
    const AL_MUZZAMMIL = 73;
    const AL_MUDDATHTHIR = 74;
    const AL_QIYAMA = 75;
    const AL_INSAN = 76;
    const AL_MURSALAT = 77;
    const AN_NABA = 78;
    const AN_NAZIAT = 79;
    const ABASA = 80;
    const AT_TAKWIR = 81;
    const AL_INFITHAR = 82;
    const AL_MUTAFFIFIN = 83;
    const AL_INSHIQAQ = 84;
    const AL_BURUJ = 85;
    const AT_TARIQ = 86;
    const AL_ALA = 87;
    const AL_GHASHIYA = 88;
    const AL_FAJR = 89;
    const AL_BALAD = 90;
    const ASH_SHAMS = 91;
    const AL_LAIL = 92;
    const ADH_DHUHA = 93;
    const AL_INSYIRAH = 94;
    const AT_TIN = 95;
    const AL_ALAQ = 96;
    const AL_QADR = 97;
    const AL_BAYYINA = 98;
    const AZ_ZALZALA = 99;
    const AL_ADIYAT = 100;
    const AL_QARIA = 101;
    const AT_TAKATHUR = 102;
    const AL_ASR = 103;
    const AL_HUMAZA = 104;
    const AL_FIL = 105;
    const QURAISY = 106;
    const AL_MAUN = 107;
    const AL_KAUTHAR = 108;
    const AL_KAFIRUN = 109;
    const AN_NASR = 110;
    const AL_LAHAB = 111;
    const AL_IKHLAS = 112;
    const AL_FALAQ = 113;
    const AN_NAS = 114;

    public static $totalAyat = [
        self::AL_FATIHAH => 7,
        self::AL_BAQARAH => 286,
        self::ALI_IMRAN => 200,
        self::AN_NISA => 176,
        self::AL_MAIDAH => 120,
        self::AL_ANAM => 165,
        self::AL_ARAF => 206,
        self::AL_ANFAL => 75,
        self::AT_TAUBAH => 129,
        self::YUNUS => 109,
        self::HUD => 123,
        self::YUSUF => 111,
        self::AR_RAD => 43,
        self::IBRAHIM => 52,
        self::AL_HIJR => 99,
        self::AN_NAHL => 128,
        self::AL_ISRA => 111,
        self::AL_KAHF => 110,
        self::MARYAM => 98,
        self::TAHA => 135,
        self::AL_ANBIYA => 112,
        self::AL_HAJJ => 78,
        self::AL_MUUMINUN => 118,
        self::AN_NUR => 64,
        self::AL_FURQAN => 77,
        self::ASH_SHUARA => 227,
        self::AN_NAML => 93,
        self::AL_QASAS => 88,
        self::AL_ANKABUT => 69,
        self::AR_RUM => 60,
        self::LUQMAN => 34,
        self::AS_SAJDAH => 30,
        self::AL_AHZAB => 73,
        self::SABA => 54,
        self::FATIR => 45,
        self::YA_SIN => 83,
        self::ASH_SAFFAT => 182,
        self::SAD => 88,
        self::AZ_ZUMAR => 75,
        self::GHAFIR => 85,
        self::FUSSILAT => 54,
        self::ASH_SHURA => 53,
        self::AZ_ZUKHRUF => 89,
        self::AD_DUKHAN => 59,
        self::AL_JATHIYA => 37,
        self::AL_AHQAF => 35,
        self::MUHAMMAD => 38,
        self::AL_FATH => 29,
        self::AL_HUJURAT => 18,
        self::QAF => 45,
        self::ADH_DHARIYAT => 60,
        self::AT_TUR => 49,
        self::AN_NAJM => 62,
        self::AL_QAMAR => 55,
        self::AR_RAHMAN => 78,
        self::AL_WAQIA => 96,
        self::AL_HADID => 29,
        self::AL_MUJADILA => 22,
        self::AL_HASHR => 24,
        self::AL_MUMTAHINA => 13,
        self::AS_SAFF => 14,
        self::AL_JUMUAH => 11,
        self::AL_MUNAFIQUN => 11,
        self::AT_TAGHABUN => 18,
        self::AT_TALAQ => 12,
        self::AT_TAHRIM => 12,
        self::AL_MULK => 30,
        self::AL_QALAM => 52,
        self::AL_HAAQQA => 52,
        self::AL_MAARIJ => 44,
        self::NUH => 28,
        self::AL_JINN => 28,
        self::AL_MUZZAMMIL => 20,
        self::AL_MUDDATHTHIR => 56,
        self::AL_QIYAMA => 40,
        self::AL_INSAN => 31,
        self::AL_MURSALAT => 50,
        self::AN_NABA => 40,
        self::AN_NAZIAT => 46,
        self::ABASA => 42,
        self::AT_TAKWIR => 29,
        self::AL_INFITHAR => 19,
        self::AL_MUTAFFIFIN => 36,
        self::AL_INSHIQAQ => 25,
        self::AL_BURUJ => 22,
        self::AT_TARIQ => 17,
        self::AL_ALA => 19,
        self::AL_GHASHIYA => 26,
        self::AL_FAJR => 30,
        self::AL_BALAD => 20,
        self::ASH_SHAMS => 15,
        self::AL_LAIL => 21,
        self::ADH_DHUHA => 11,
        self::AL_INSYIRAH => 8,
        self::AT_TIN => 8,
        self::AL_ALAQ => 19,
        self::AL_QADR => 5,
        self::AL_BAYYINA => 8,
        self::AZ_ZALZALA => 8,
        self::AL_ADIYAT => 11,
        self::AL_QARIA => 11,
        self::AT_TAKATHUR => 8,
        self::AL_ASR => 3,
        self::AL_HUMAZA => 9,
        self::AL_FIL => 5,
        self::QURAISY => 4,
        self::AL_MAUN => 7,
        self::AL_KAUTHAR => 3,
        self::AL_KAFIRUN => 6,
        self::AN_NASR => 3,
        self::AL_LAHAB => 5,
        self::AL_IKHLAS => 4,
        self::AL_FALAQ => 5,
        self::AN_NAS => 6,
    ];
}
